### ISSUE TITLE
0.9.2存在问题，需要安装ps

### ISSUE THREAD

**Issue by deadash** [soulteary/docker-cronicle#1]
如题，使用0.9.2会报错

在 docker 里面 添加 `RUN apk add --no-cache procps` 就可以解决了。

**Comment by soulteary** [comment]
你好👋，我刚刚审查了下 https://github.com/jhuckaby/Cronicle/commits/master 最近的代码。

发现作者并未进行任何有效修改，仅仅是变更了部分依赖版本和替换了 `mkdirp` 实现，以及重申项目当前状态不接受 PR，同作为用户，我不建议进行升级。 @deadash
