### ISSUE TITLE
Persistent Server Issue

### ISSUE THREAD

**Issue by bryant7392** [soulteary/docker-cronicle#11]
I seem to be having an issue where everytime restart the container all the servers seem to dissapear except for the main server. 

i have my volumes setup as below.  I can see json populating the server data but then after i restart it reverts.  Any ideas?

      - /mnt/docker-share/cronicle/data:/opt/cronicle/data:rw
      - /mnt/docker-share/cronicle/logs:/opt/cronicle/logs:rw
      - /mnt/docker-share/cronicle/plugins:/opt/cronicle/plugins:rw
      - /mnt/docker-share/cronicle/conf/config.json:/opt/cronicle/conf/config.json:rw

**Comment by bryant7392** [comment]
Just to add further clarification.  The file in /opt/cronicle/data/global/af/56/5a/af565a097a0cf8d7d5855ecc92c24c34.json reverts everytime i restart the container.  This file contains the servers that i add into the Cronicle Web UI.  I can see it updating properly in my persistent folder under /mnt/docker-share/cronicle directory but it reverts on restart.  Thanks!

**Comment by GaneshParkopedia** [comment]
It looks like the current setup doesn't support multiple workers.

If you see [this page on the cronicle docs](https://github.com/jhuckaby/Cronicle/blob/master/docs/Setup.md#single-primary-with-workers), it says `bin/control.sh setup` should not be run on worker nodes. 

It is running that in [the Dockerfile for this project](https://github.com/soulteary/docker-cronicle/blob/main/docker/Dockerfile#L23C1-L23C51). Unfortunately it isn't as simple as just creating a separate Dockerfile for this as the [command run at start (entrypoint)](https://github.com/soulteary/docker-cronicle/blob/main/docker/docker-entrypoint.js) seems to be specific for the master node as well.

So I *think* what is happening is that all servers are trying to be master, they are overwriting your configuration.
