### ISSUE TITLE
Workers support

### ISSUE THREAD

**Issue by GaneshParkopedia** [soulteary/docker-cronicle#12]
Hi! Thanks for your work on this, looks great, especially having ARM support!

# Motivation

I would like to run a single primary with multiple workers. I don't want the workers to be able to configure new jobs on other servers, edit existing configurations or add new servers. Cronicle itself supports this, but it seems like this project does not. 

This is somewhat related to [this issue](https://github.com/soulteary/docker-cronicle/issues/11).

# Description

If you see [this page on the cronicle docs](https://github.com/jhuckaby/Cronicle/blob/master/docs/Setup.md#single-primary-with-workers), it says `bin/control.sh setup` should not be run on worker nodes. 

It is running that in [the Dockerfile for this project](https://github.com/soulteary/docker-cronicle/blob/main/docker/Dockerfile#L23C1-L23C51). Unfortunately it isn't as simple as just creating a separate Dockerfile (or build stage) for this as the [command run at start (entrypoint)](https://github.com/soulteary/docker-cronicle/blob/main/docker/docker-entrypoint.js) seems to be specific for the master node as well.

**Comment by soulteary** [comment]
This is an interesting problem, and it is actually relatively easy to solve. You only need to slightly adjust the patch program to distinguish between worker and master instances.

You can make adjustments based on this idea. PRs are welcome back to this project or the original project.

**Comment by pradyumnvermaa** [comment]
Hello @soulteary , can you please suggest how to slightly adjust the patch program to distinguish between worker and master instances?

**Comment by soulteary** [comment]
@GaneshParkopedia okay, when I have time later, I will write an article to introduce how to use it, as well as the use of cronic containers to execute various programs often mentioned in another issue.
