### ISSUE TITLE
有arm64的版本吗

### ISSUE THREAD

**Issue by dreampjk** [soulteary/docker-cronicle#17]
docker run \
        -v /etc/localtime:/etc/localtime:ro \
        -v /etc/timezone:/etc/timezone:ro \
        -v `pwd`/media/docker/cronicle/data:/opt/cronicle/data:rw \
        -v `pwd`/media/docker/cronicle/logs:/opt/cronicle/logs:rw \
        -v `pwd`/media/docker/cronicle/plugins:/opt/cronicle/plugins:rw \
        -p 3012:3012 \
        --hostname cronicle \
        --name cronicle \
        soulteary/cronicle:arm64

哪里写错了吗  下载不了

**Comment by soulteary** [comment]
Construction with multi -architecture, you can directly pull, no need to add a specified platform.

使用了多架构构建，直接 pull 即可，不需要添加指定平台。
