### ISSUE TITLE
ARM version

### ISSUE THREAD

**Issue by zmactep** [soulteary/docker-cronicle#3]
Hi!

Thank you for your work. The container is running great for me. I've found that `arm` version of the container can be built without any changes in the Dockerfile, so can I ask you to push arm container to a docker hub?

**Comment by soulteary** [comment]
Thanks for the suggestion

I'm considering whether to introduce a simple build ci.

If anyone has an idea, please provide a pr

**Comment by soulteary** [comment]
WIP https://github.com/soulteary/docker-cronicle/issues/7
