### ISSUE TITLE
Job failed with error: Script failed: No such file or directory

### ISSUE THREAD

**Issue by ovizii** [soulteary/docker-cronicle#5]
I am trying my hand at running your image and my first test when using the shell script plugin was to run a simple ping 5x and it works. 

Now I am trying to run a slightly more complex script and it fails with this error: 

```
# Job failed with error: Script failed: No such file or directory (spawn /tmp/cronicle-script-temp-jlgi3hay503.sh ENOENT)
# 1 retries remain (1 min delay)
```

All I can find when googling that is this, but I am not sure how to fix it or if it is my script at fault: 
https://github.com/jhuckaby/Cronicle/issues/587 
https://github.com/jhuckaby/Cronicle/issues/133

They are talking about the /tmp folder possibly being protected from code being executed, but then why would the first test wit ha simple ping work?

Working example:
![image](https://user-images.githubusercontent.com/837902/232233209-5f2dafbc-8519-4bf8-a2c2-e66403e62f66.png)

Problematic example:
```
#!/bin/bash
if curl -I "https://sub1.domain.tld/login.html" 2>&1 | grep -w "200\|301" ; then
   curl "https://sub1.domain.tld/login.html" -s -o /dev/null -w "%{time_total}" | xargs -I [] curl -k -s "https://sub2.domain.tld/api/push/secret?msg=OK&ping=[]"
else
   curl -k -s "https://sub2.domain.tld/api/push/secret?status=down"
fi
```

I'd appreciate any pointers.

**Comment by soulteary** [comment]
Hello @ovizii , there are two best practices when I personally use:

1. Based on the current image as the base image, build images with curl, wget, and even python, which can execute complex scripts
2. Only use this image to call other programs for execution, stripping the complexity, and this program is only used as a trigger

**Comment by ovizii** [comment]
Ah, I see. Sounds logical and doable, as originally I had a script which I was calling via crontab, so I guess I can just call it with this image then.

**Comment by ovizii** [comment]
OK, need to add a second question after reading your reply to https://github.com/soulteary/docker-cronicle/issues/6 

So you mean, I can just mount a volume into this container which contains the scripts I want to call on the docker host, right?

**Comment by soulteary** [comment]
I saw this issue was opened again, maybe what's missing here is a simple blog post or best practice :)

// Sorry for being overwhelmed by thousands of squeezed issues, did not see the message reminder @ovizii

**Comment by a-reda** [comment]
> 2. Only use this image to call other programs for execution, stripping the complexity, and this program is only used as a trigger

@soulteary 
How would you trigger a script in the host machine?

**Comment by soulteary** [comment]
> > 2. Only use this image to call other programs for execution, stripping the complexity, and this program is only used as a trigger
> 
> @soulteary How would you trigger a script in the host machine? using ssh?

hey, I usually use a webhook software, I remember I pushed a fork project, you can search for it on my personal page.

**Comment by BossBele** [comment]
For me, I had accidentally used `#!/bin/bash` at the top of the script instead of `#!/bin/sh` which is automatically inserted in the shell plugin.
Sometimes, simple mistakes like this could cause nightmares. Perhaps this would be helpful to some.
