### ISSUE TITLE
Is there an option to be able to run scripts on the host itself?

### ISSUE THREAD

**Issue by ovizii** [soulteary/docker-cronicle#6]
Say you want to run scripts on the host but don't want to clutter the host with the installation of cronicle, is this feasible or not worth the effort to run cronicle in a container and then make the effort to "let it out of the container"? :-)

**Comment by soulteary** [comment]
Yes, just refer to the second solution in the previous issue https://github.com/soulteary/docker-cronicle/issues/5 , you can even call the script of the host machine in the container
