### ISSUE TITLE
It doesn't show cron jobs already created

### ISSUE THREAD

**Issue by johnnyaussi** [soulteary/docker-cronicle#8]
I installed cronicle as a docker container via the yml file

The problem is that the webGUi doesn't show cron jobs I had already created before installing cronicle.

Can it be fixed somehow?

Thanks

**Comment by soulteary** [comment]
cannot reproduce, with the latest version, everything seems to work fine.

maybe you should redownload the image

```
docker pull soulteary/cronicle:0.9.21
```



<img width="1024" alt="image" src="https://github.com/soulteary/docker-cronicle/assets/1500781/8f0cd8e2-ccda-46bd-85a8-286ced738e35">

<img width="1515" alt="image" src="https://github.com/soulteary/docker-cronicle/assets/1500781/86ba1991-4a17-4db6-9813-4e1fa7b5d2dc">

**Comment by johnnyaussi** [comment]
Nope! It still shows no event in the schedule window, or elsewhere
